/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiV3AvgPriceGet200Response {
    #[serde(rename = "mins")]
    pub mins: i64,
    #[serde(rename = "price")]
    pub price: String,
}

impl ApiV3AvgPriceGet200Response {
    pub fn new(mins: i64, price: String) -> ApiV3AvgPriceGet200Response {
        ApiV3AvgPriceGet200Response {
            mins,
            price,
        }
    }
}


