/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1LendingUnionPurchaseRecordGet200Response {
}

impl SapiV1LendingUnionPurchaseRecordGet200Response {
    pub fn new() -> SapiV1LendingUnionPurchaseRecordGet200Response {
        SapiV1LendingUnionPurchaseRecordGet200Response {
        }
    }
}


