/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1MarginLoanGet200ResponseRowsInner {
    #[serde(rename = "isolatedSymbol")]
    pub isolated_symbol: String,
    #[serde(rename = "txId")]
    pub tx_id: i64,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "principal")]
    pub principal: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "status")]
    pub status: String,
}

impl SapiV1MarginLoanGet200ResponseRowsInner {
    pub fn new(isolated_symbol: String, tx_id: i64, asset: String, principal: String, timestamp: i64, status: String) -> SapiV1MarginLoanGet200ResponseRowsInner {
        SapiV1MarginLoanGet200ResponseRowsInner {
            isolated_symbol,
            tx_id,
            asset,
            principal,
            timestamp,
            status,
        }
    }
}


