/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV2SubAccountFuturesAccountSummaryGet200Response {
    #[serde(rename = "futureAccountSummaryResp")]
    pub future_account_summary_resp: Box<crate::models::SubAccountUsdtFuturesSummaryFutureAccountSummaryResp>,
    #[serde(rename = "deliveryAccountSummaryResp")]
    pub delivery_account_summary_resp: Box<crate::models::SubAccountCoinFuturesSummaryDeliveryAccountSummaryResp>,
}

impl SapiV2SubAccountFuturesAccountSummaryGet200Response {
    pub fn new(future_account_summary_resp: crate::models::SubAccountUsdtFuturesSummaryFutureAccountSummaryResp, delivery_account_summary_resp: crate::models::SubAccountCoinFuturesSummaryDeliveryAccountSummaryResp) -> SapiV2SubAccountFuturesAccountSummaryGet200Response {
        SapiV2SubAccountFuturesAccountSummaryGet200Response {
            future_account_summary_resp: Box::new(future_account_summary_resp),
            delivery_account_summary_resp: Box::new(delivery_account_summary_resp),
        }
    }
}


