/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapPoolConfigureGet200ResponseInnerLiquidity {
    /// \"NA\" if pool is an innovation pool
    #[serde(rename = "constantA")]
    pub constant_a: i64,
    #[serde(rename = "minRedeemShare")]
    pub min_redeem_share: f64,
    /// The swap proceeds only when the slippage is within the set range
    #[serde(rename = "slippageTolerance")]
    pub slippage_tolerance: f64,
}

impl SapiV1BswapPoolConfigureGet200ResponseInnerLiquidity {
    pub fn new(constant_a: i64, min_redeem_share: f64, slippage_tolerance: f64) -> SapiV1BswapPoolConfigureGet200ResponseInnerLiquidity {
        SapiV1BswapPoolConfigureGet200ResponseInnerLiquidity {
            constant_a,
            min_redeem_share,
            slippage_tolerance,
        }
    }
}


