/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1StakingProductListGet200ResponseInnerDetail {
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "rewardAsset")]
    pub reward_asset: String,
    #[serde(rename = "duration")]
    pub duration: i64,
    #[serde(rename = "renewable")]
    pub renewable: bool,
    #[serde(rename = "apy")]
    pub apy: String,
}

impl SapiV1StakingProductListGet200ResponseInnerDetail {
    pub fn new(asset: String, reward_asset: String, duration: i64, renewable: bool, apy: String) -> SapiV1StakingProductListGet200ResponseInnerDetail {
        SapiV1StakingProductListGet200ResponseInnerDetail {
            asset,
            reward_asset,
            duration,
            renewable,
            apy,
        }
    }
}


