/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1FuturesLoanAdjustCollateralHistoryGet200Response {
    #[serde(rename = "rows")]
    pub rows: Vec<crate::models::SapiV1FuturesLoanAdjustCollateralHistoryGet200ResponseRowsInner>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl SapiV1FuturesLoanAdjustCollateralHistoryGet200Response {
    pub fn new(rows: Vec<crate::models::SapiV1FuturesLoanAdjustCollateralHistoryGet200ResponseRowsInner>, total: i64) -> SapiV1FuturesLoanAdjustCollateralHistoryGet200Response {
        SapiV1FuturesLoanAdjustCollateralHistoryGet200Response {
            rows,
            total,
        }
    }
}


