/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1MarginRepayGet200ResponseRowsInner {
    /// Isolated symbol, will not be returned for crossed margin
    #[serde(rename = "isolatedSymbol")]
    pub isolated_symbol: String,
    /// Total amount repaid
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "asset")]
    pub asset: String,
    /// Interest repaid
    #[serde(rename = "interest")]
    pub interest: String,
    /// Principal repaid
    #[serde(rename = "principal")]
    pub principal: String,
    /// One of PENDING (pending execution), CONFIRMED (successfully execution), FAILED (execution failed, nothing happened to your account)
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "txId")]
    pub tx_id: i64,
}

impl SapiV1MarginRepayGet200ResponseRowsInner {
    pub fn new(isolated_symbol: String, amount: String, asset: String, interest: String, principal: String, status: String, timestamp: i64, tx_id: i64) -> SapiV1MarginRepayGet200ResponseRowsInner {
        SapiV1MarginRepayGet200ResponseRowsInner {
            isolated_symbol,
            amount,
            asset,
            interest,
            principal,
            status,
            timestamp,
            tx_id,
        }
    }
}


