/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapSwapGet200Response {
    #[serde(rename = "swapId")]
    pub swap_id: i64,
}

impl SapiV1BswapSwapGet200Response {
    pub fn new(swap_id: i64) -> SapiV1BswapSwapGet200Response {
        SapiV1BswapSwapGet200Response {
            swap_id,
        }
    }
}


