/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapClaimedHistoryGet200ResponseInner {
    #[serde(rename = "poolId")]
    pub pool_id: i32,
    #[serde(rename = "poolName")]
    pub pool_name: String,
    #[serde(rename = "assetRewards")]
    pub asset_rewards: String,
    #[serde(rename = "claimTime")]
    pub claim_time: i64,
    #[serde(rename = "claimAmount")]
    pub claim_amount: f32,
    /// 0: pending, 1: success
    #[serde(rename = "status")]
    pub status: i32,
}

impl SapiV1BswapClaimedHistoryGet200ResponseInner {
    pub fn new(pool_id: i32, pool_name: String, asset_rewards: String, claim_time: i64, claim_amount: f32, status: i32) -> SapiV1BswapClaimedHistoryGet200ResponseInner {
        SapiV1BswapClaimedHistoryGet200ResponseInner {
            pool_id,
            pool_name,
            asset_rewards,
            claim_time,
            claim_amount,
            status,
        }
    }
}


