/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1FuturesLoanBorrowHistoryGet200ResponseRowsInner {
    #[serde(rename = "confirmedTime")]
    pub confirmed_time: i64,
    #[serde(rename = "coin")]
    pub coin: String,
    #[serde(rename = "collateralRate")]
    pub collateral_rate: String,
    #[serde(rename = "leftTotal")]
    pub left_total: String,
    #[serde(rename = "leftPrincipal")]
    pub left_principal: String,
    #[serde(rename = "deadline")]
    pub deadline: i64,
    #[serde(rename = "collateralCoin")]
    pub collateral_coin: String,
    #[serde(rename = "collateralAmount")]
    pub collateral_amount: String,
    #[serde(rename = "orderStatus")]
    pub order_status: String,
    #[serde(rename = "borrowId")]
    pub borrow_id: String,
}

impl SapiV1FuturesLoanBorrowHistoryGet200ResponseRowsInner {
    pub fn new(confirmed_time: i64, coin: String, collateral_rate: String, left_total: String, left_principal: String, deadline: i64, collateral_coin: String, collateral_amount: String, order_status: String, borrow_id: String) -> SapiV1FuturesLoanBorrowHistoryGet200ResponseRowsInner {
        SapiV1FuturesLoanBorrowHistoryGet200ResponseRowsInner {
            confirmed_time,
            coin,
            collateral_rate,
            left_total,
            left_principal,
            deadline,
            collateral_coin,
            collateral_amount,
            order_status,
            borrow_id,
        }
    }
}


