/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV2SubAccountFuturesPositionRiskGet200Response {
    #[serde(rename = "futurePositionRiskVos")]
    pub future_position_risk_vos: Vec<crate::models::SapiV1SubAccountFuturesPositionRiskGet200ResponseInner>,
    #[serde(rename = "deliveryPositionRiskVos")]
    pub delivery_position_risk_vos: Vec<crate::models::SubAccountCoinFuturesPositionRiskDeliveryPositionRiskVosInner>,
}

impl SapiV2SubAccountFuturesPositionRiskGet200Response {
    pub fn new(future_position_risk_vos: Vec<crate::models::SapiV1SubAccountFuturesPositionRiskGet200ResponseInner>, delivery_position_risk_vos: Vec<crate::models::SubAccountCoinFuturesPositionRiskDeliveryPositionRiskVosInner>) -> SapiV2SubAccountFuturesPositionRiskGet200Response {
        SapiV2SubAccountFuturesPositionRiskGet200Response {
            future_position_risk_vos,
            delivery_position_risk_vos,
        }
    }
}


