/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV2FuturesLoanWalletGet200Response {
    #[serde(rename = "totalCrossCollateral")]
    pub total_cross_collateral: String,
    #[serde(rename = "totalBorrowed")]
    pub total_borrowed: String,
    #[serde(rename = "totalInterest")]
    pub total_interest: String,
    #[serde(rename = "interestFreeLimit")]
    pub interest_free_limit: String,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "crossCollaterals")]
    pub cross_collaterals: Vec<crate::models::SapiV2FuturesLoanWalletGet200ResponseCrossCollateralsInner>,
}

impl SapiV2FuturesLoanWalletGet200Response {
    pub fn new(total_cross_collateral: String, total_borrowed: String, total_interest: String, interest_free_limit: String, asset: String, cross_collaterals: Vec<crate::models::SapiV2FuturesLoanWalletGet200ResponseCrossCollateralsInner>) -> SapiV2FuturesLoanWalletGet200Response {
        SapiV2FuturesLoanWalletGet200Response {
            total_cross_collateral,
            total_borrowed,
            total_interest,
            interest_free_limit,
            asset,
            cross_collaterals,
        }
    }
}


