/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1StakingProductListGet200ResponseInner {
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "detail")]
    pub detail: Box<crate::models::SapiV1StakingProductListGet200ResponseInnerDetail>,
    #[serde(rename = "quota")]
    pub quota: Box<crate::models::SapiV1StakingProductListGet200ResponseInnerQuota>,
}

impl SapiV1StakingProductListGet200ResponseInner {
    pub fn new(project_id: String, detail: crate::models::SapiV1StakingProductListGet200ResponseInnerDetail, quota: crate::models::SapiV1StakingProductListGet200ResponseInnerQuota) -> SapiV1StakingProductListGet200ResponseInner {
        SapiV1StakingProductListGet200ResponseInner {
            project_id,
            detail: Box::new(detail),
            quota: Box::new(quota),
        }
    }
}


