/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1FuturesLoanAdjustCollateralHistoryGet200ResponseRowsInner {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "collateralCoin")]
    pub collateral_coin: String,
    #[serde(rename = "coin")]
    pub coin: String,
    #[serde(rename = "preCollateralRate", skip_serializing_if = "Option::is_none")]
    pub pre_collateral_rate: Option<String>,
    #[serde(rename = "afterCollateralRate", skip_serializing_if = "Option::is_none")]
    pub after_collateral_rate: Option<String>,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "adjustTime", skip_serializing_if = "Option::is_none")]
    pub adjust_time: Option<i64>,
}

impl SapiV1FuturesLoanAdjustCollateralHistoryGet200ResponseRowsInner {
    pub fn new(amount: String, collateral_coin: String, coin: String, status: String) -> SapiV1FuturesLoanAdjustCollateralHistoryGet200ResponseRowsInner {
        SapiV1FuturesLoanAdjustCollateralHistoryGet200ResponseRowsInner {
            amount,
            collateral_coin,
            coin,
            pre_collateral_rate: None,
            after_collateral_rate: None,
            direction: None,
            status,
            adjust_time: None,
        }
    }
}


