/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1StakingStakingRecordGet200ResponseInner {
    #[serde(rename = "positionId")]
    pub position_id: String,
    #[serde(rename = "time")]
    pub time: i64,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "lockPeriod")]
    pub lock_period: String,
    #[serde(rename = "deliverDate")]
    pub deliver_date: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl SapiV1StakingStakingRecordGet200ResponseInner {
    pub fn new(position_id: String, time: i64, asset: String, project: String, amount: String, lock_period: String, deliver_date: String, r#type: String, status: String) -> SapiV1StakingStakingRecordGet200ResponseInner {
        SapiV1StakingStakingRecordGet200ResponseInner {
            position_id,
            time,
            asset,
            project,
            amount,
            lock_period,
            deliver_date,
            r#type,
            status,
        }
    }
}


