/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV2FuturesLoanWalletGet200ResponseCrossCollateralsInner {
    #[serde(rename = "loanCoin")]
    pub loan_coin: String,
    #[serde(rename = "collateralCoin")]
    pub collateral_coin: String,
    #[serde(rename = "locked")]
    pub locked: String,
    #[serde(rename = "loanAmount")]
    pub loan_amount: String,
    #[serde(rename = "currentCollateralRate")]
    pub current_collateral_rate: String,
    #[serde(rename = "interestFreeLimitUsed")]
    pub interest_free_limit_used: String,
    #[serde(rename = "principalForInterest")]
    pub principal_for_interest: String,
    #[serde(rename = "interest")]
    pub interest: String,
}

impl SapiV2FuturesLoanWalletGet200ResponseCrossCollateralsInner {
    pub fn new(loan_coin: String, collateral_coin: String, locked: String, loan_amount: String, current_collateral_rate: String, interest_free_limit_used: String, principal_for_interest: String, interest: String) -> SapiV2FuturesLoanWalletGet200ResponseCrossCollateralsInner {
        SapiV2FuturesLoanWalletGet200ResponseCrossCollateralsInner {
            loan_coin,
            collateral_coin,
            locked,
            loan_amount,
            current_collateral_rate,
            interest_free_limit_used,
            principal_for_interest,
            interest,
        }
    }
}


