/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1FuturesLoanInterestHistoryGet200ResponseRowsInner {
    #[serde(rename = "collateralCoin")]
    pub collateral_coin: String,
    #[serde(rename = "interestCoin")]
    pub interest_coin: String,
    #[serde(rename = "interest")]
    pub interest: String,
    #[serde(rename = "interestFreeLimitUsed")]
    pub interest_free_limit_used: String,
    #[serde(rename = "principalForInterest")]
    pub principal_for_interest: String,
    #[serde(rename = "interestRate")]
    pub interest_rate: String,
    #[serde(rename = "time")]
    pub time: i64,
}

impl SapiV1FuturesLoanInterestHistoryGet200ResponseRowsInner {
    pub fn new(collateral_coin: String, interest_coin: String, interest: String, interest_free_limit_used: String, principal_for_interest: String, interest_rate: String, time: i64) -> SapiV1FuturesLoanInterestHistoryGet200ResponseRowsInner {
        SapiV1FuturesLoanInterestHistoryGet200ResponseRowsInner {
            collateral_coin,
            interest_coin,
            interest,
            interest_free_limit_used,
            principal_for_interest,
            interest_rate,
            time,
        }
    }
}


