/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1MarginDribbletGet200Response {
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "userAssetDribblets")]
    pub user_asset_dribblets: Vec<crate::models::SapiV1MarginDribbletGet200ResponseUserAssetDribbletsInner>,
}

impl SapiV1MarginDribbletGet200Response {
    pub fn new(total: i64, user_asset_dribblets: Vec<crate::models::SapiV1MarginDribbletGet200ResponseUserAssetDribbletsInner>) -> SapiV1MarginDribbletGet200Response {
        SapiV1MarginDribbletGet200Response {
            total,
            user_asset_dribblets,
        }
    }
}


