/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapUnclaimedRewardsGet200Response {
    #[serde(rename = "totalUnclaimedRewards")]
    pub total_unclaimed_rewards: Box<crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseTotalUnclaimedRewards>,
    #[serde(rename = "details")]
    pub details: Box<crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseDetails>,
}

impl SapiV1BswapUnclaimedRewardsGet200Response {
    pub fn new(total_unclaimed_rewards: crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseTotalUnclaimedRewards, details: crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseDetails) -> SapiV1BswapUnclaimedRewardsGet200Response {
        SapiV1BswapUnclaimedRewardsGet200Response {
            total_unclaimed_rewards: Box::new(total_unclaimed_rewards),
            details: Box::new(details),
        }
    }
}


