/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1AssetConvertTransferQueryByPagePost200Response {
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "rows")]
    pub rows: Vec<crate::models::SapiV1AssetConvertTransferQueryByPagePost200ResponseRowsInner>,
}

impl SapiV1AssetConvertTransferQueryByPagePost200Response {
    pub fn new(total: i32, rows: Vec<crate::models::SapiV1AssetConvertTransferQueryByPagePost200ResponseRowsInner>) -> SapiV1AssetConvertTransferQueryByPagePost200Response {
        SapiV1AssetConvertTransferQueryByPagePost200Response {
            total,
            rows,
        }
    }
}


