/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapUnclaimedRewardsGet200ResponseDetails {
    #[serde(rename = "BNB/USDT")]
    pub bnb_slash_usdt: Box<crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbUsdt>,
    #[serde(rename = "BNB/BTC")]
    pub bnb_slash_btc: Box<crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbBtc>,
}

impl SapiV1BswapUnclaimedRewardsGet200ResponseDetails {
    pub fn new(bnb_slash_usdt: crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbUsdt, bnb_slash_btc: crate::models::SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbBtc) -> SapiV1BswapUnclaimedRewardsGet200ResponseDetails {
        SapiV1BswapUnclaimedRewardsGet200ResponseDetails {
            bnb_slash_usdt: Box::new(bnb_slash_usdt),
            bnb_slash_btc: Box::new(bnb_slash_btc),
        }
    }
}


