/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigure {
    #[serde(rename = "BUSD")]
    pub busd: Box<crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigureBusd>,
    #[serde(rename = "USDT")]
    pub usdt: Box<crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigureBusd>,
}

impl SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigure {
    pub fn new(busd: crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigureBusd, usdt: crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigureBusd) -> SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigure {
        SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigure {
            busd: Box::new(busd),
            usdt: Box::new(usdt),
        }
    }
}


