/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1FuturesLoanLiquidationHistoryGet200ResponseRowsInner {
    #[serde(rename = "collateralAmountForLiquidation")]
    pub collateral_amount_for_liquidation: String,
    #[serde(rename = "collateralCoin")]
    pub collateral_coin: String,
    #[serde(rename = "forceLiquidationStartTime")]
    pub force_liquidation_start_time: i64,
    #[serde(rename = "coin")]
    pub coin: String,
    #[serde(rename = "restCollateralAmountAfterLiquidation")]
    pub rest_collateral_amount_after_liquidation: String,
    #[serde(rename = "restLoanAmount")]
    pub rest_loan_amount: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl SapiV1FuturesLoanLiquidationHistoryGet200ResponseRowsInner {
    pub fn new(collateral_amount_for_liquidation: String, collateral_coin: String, force_liquidation_start_time: i64, coin: String, rest_collateral_amount_after_liquidation: String, rest_loan_amount: String, status: String) -> SapiV1FuturesLoanLiquidationHistoryGet200ResponseRowsInner {
        SapiV1FuturesLoanLiquidationHistoryGet200ResponseRowsInner {
            collateral_amount_for_liquidation,
            collateral_coin,
            force_liquidation_start_time,
            coin,
            rest_collateral_amount_after_liquidation,
            rest_loan_amount,
            status,
        }
    }
}


