/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapPoolConfigureGet200ResponseInner {
    #[serde(rename = "poolId")]
    pub pool_id: i64,
    #[serde(rename = "poolNmae")]
    pub pool_nmae: String,
    #[serde(rename = "updateTime")]
    pub update_time: i64,
    #[serde(rename = "liquidity")]
    pub liquidity: Box<crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerLiquidity>,
    #[serde(rename = "assetConfigure")]
    pub asset_configure: Box<crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigure>,
}

impl SapiV1BswapPoolConfigureGet200ResponseInner {
    pub fn new(pool_id: i64, pool_nmae: String, update_time: i64, liquidity: crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerLiquidity, asset_configure: crate::models::SapiV1BswapPoolConfigureGet200ResponseInnerAssetConfigure) -> SapiV1BswapPoolConfigureGet200ResponseInner {
        SapiV1BswapPoolConfigureGet200ResponseInner {
            pool_id,
            pool_nmae,
            update_time,
            liquidity: Box::new(liquidity),
            asset_configure: Box::new(asset_configure),
        }
    }
}


