/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1LendingDailyUserLeftQuotaGet200Response {
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "leftQuota")]
    pub left_quota: String,
}

impl SapiV1LendingDailyUserLeftQuotaGet200Response {
    pub fn new(asset: String, left_quota: String) -> SapiV1LendingDailyUserLeftQuotaGet200Response {
        SapiV1LendingDailyUserLeftQuotaGet200Response {
            asset,
            left_quota,
        }
    }
}


