/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1LendingDailyProductListGet200ResponseInner {
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "avgAnnualInterestRate")]
    pub avg_annual_interest_rate: String,
    #[serde(rename = "canPurchase")]
    pub can_purchase: bool,
    #[serde(rename = "canRedeem")]
    pub can_redeem: bool,
    #[serde(rename = "dailyInterestPerThousand")]
    pub daily_interest_per_thousand: String,
    #[serde(rename = "featured")]
    pub featured: bool,
    #[serde(rename = "minPurchaseAmount")]
    pub min_purchase_amount: String,
    #[serde(rename = "productId")]
    pub product_id: String,
    #[serde(rename = "purchasedAmount")]
    pub purchased_amount: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "upLimit")]
    pub up_limit: String,
    #[serde(rename = "upLimitPerUser")]
    pub up_limit_per_user: String,
}

impl SapiV1LendingDailyProductListGet200ResponseInner {
    pub fn new(asset: String, avg_annual_interest_rate: String, can_purchase: bool, can_redeem: bool, daily_interest_per_thousand: String, featured: bool, min_purchase_amount: String, product_id: String, purchased_amount: String, status: String, up_limit: String, up_limit_per_user: String) -> SapiV1LendingDailyProductListGet200ResponseInner {
        SapiV1LendingDailyProductListGet200ResponseInner {
            asset,
            avg_annual_interest_rate,
            can_purchase,
            can_redeem,
            daily_interest_per_thousand,
            featured,
            min_purchase_amount,
            product_id,
            purchased_amount,
            status,
            up_limit,
            up_limit_per_user,
        }
    }
}


