/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapPoolsGet200ResponseInner {
    #[serde(rename = "poolId")]
    pub pool_id: i64,
    #[serde(rename = "poolName")]
    pub pool_name: String,
    #[serde(rename = "assets")]
    pub assets: Vec<String>,
}

impl SapiV1BswapPoolsGet200ResponseInner {
    pub fn new(pool_id: i64, pool_name: String, assets: Vec<String>) -> SapiV1BswapPoolsGet200ResponseInner {
        SapiV1BswapPoolsGet200ResponseInner {
            pool_id,
            pool_name,
            assets,
        }
    }
}


