/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapLiquidityGet200ResponseInnerShare {
    #[serde(rename = "shareAmount")]
    pub share_amount: f64,
    #[serde(rename = "sharePercentage")]
    pub share_percentage: f64,
    #[serde(rename = "asset")]
    pub asset: Box<crate::models::SapiV1BswapLiquidityGet200ResponseInnerShareAsset>,
}

impl SapiV1BswapLiquidityGet200ResponseInnerShare {
    pub fn new(share_amount: f64, share_percentage: f64, asset: crate::models::SapiV1BswapLiquidityGet200ResponseInnerShareAsset) -> SapiV1BswapLiquidityGet200ResponseInnerShare {
        SapiV1BswapLiquidityGet200ResponseInnerShare {
            share_amount,
            share_percentage,
            asset: Box::new(asset),
        }
    }
}


