/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbUsdt {
    #[serde(rename = "BUSD")]
    pub busd: f32,
    #[serde(rename = "USDT")]
    pub usdt: f64,
}

impl SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbUsdt {
    pub fn new(busd: f32, usdt: f64) -> SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbUsdt {
        SapiV1BswapUnclaimedRewardsGet200ResponseDetailsBnbUsdt {
            busd,
            usdt,
        }
    }
}


