/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1FuturesLoanRepayHistoryGet200ResponseRowsInner {
    #[serde(rename = "coin")]
    pub coin: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "collateralCoin")]
    pub collateral_coin: String,
    #[serde(rename = "repayType")]
    pub repay_type: String,
    #[serde(rename = "releasedCollateral")]
    pub released_collateral: String,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "repayCollateral")]
    pub repay_collateral: String,
    #[serde(rename = "confirmedTime")]
    pub confirmed_time: i64,
    #[serde(rename = "updateTime")]
    pub update_time: i64,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "repayId")]
    pub repay_id: String,
}

impl SapiV1FuturesLoanRepayHistoryGet200ResponseRowsInner {
    pub fn new(coin: String, amount: String, collateral_coin: String, repay_type: String, released_collateral: String, price: String, repay_collateral: String, confirmed_time: i64, update_time: i64, status: String, repay_id: String) -> SapiV1FuturesLoanRepayHistoryGet200ResponseRowsInner {
        SapiV1FuturesLoanRepayHistoryGet200ResponseRowsInner {
            coin,
            amount,
            collateral_coin,
            repay_type,
            released_collateral,
            price,
            repay_collateral,
            confirmed_time,
            update_time,
            status,
            repay_id,
        }
    }
}


