/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV2SubAccountFuturesAccountGet200Response {
    #[serde(rename = "futureAccountResp")]
    pub future_account_resp: Box<crate::models::SubAccountUsdtFuturesDetailsFutureAccountResp>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "assets")]
    pub assets: Vec<crate::models::SubAccountCoinFuturesDetailsAssetsInner>,
    #[serde(rename = "canDeposit")]
    pub can_deposit: bool,
    #[serde(rename = "canTrade")]
    pub can_trade: bool,
    #[serde(rename = "canWithdraw")]
    pub can_withdraw: bool,
    #[serde(rename = "feeTier")]
    pub fee_tier: i64,
    #[serde(rename = "updateTime")]
    pub update_time: i64,
}

impl SapiV2SubAccountFuturesAccountGet200Response {
    pub fn new(future_account_resp: crate::models::SubAccountUsdtFuturesDetailsFutureAccountResp, email: String, assets: Vec<crate::models::SubAccountCoinFuturesDetailsAssetsInner>, can_deposit: bool, can_trade: bool, can_withdraw: bool, fee_tier: i64, update_time: i64) -> SapiV2SubAccountFuturesAccountGet200Response {
        SapiV2SubAccountFuturesAccountGet200Response {
            future_account_resp: Box::new(future_account_resp),
            email,
            assets,
            can_deposit,
            can_trade,
            can_withdraw,
            fee_tier,
            update_time,
        }
    }
}


