/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SapiV1LendingDailyTokenPositionGet200ResponseInner {
    #[serde(rename = "annualInterestRate")]
    pub annual_interest_rate: String,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "avgAnnualInterestRate")]
    pub avg_annual_interest_rate: String,
    #[serde(rename = "canRedeem")]
    pub can_redeem: bool,
    #[serde(rename = "dailyInterestRate")]
    pub daily_interest_rate: String,
    #[serde(rename = "freeAmount")]
    pub free_amount: String,
    #[serde(rename = "freezeAmount")]
    pub freeze_amount: String,
    #[serde(rename = "lockedAmount")]
    pub locked_amount: String,
    #[serde(rename = "productId")]
    pub product_id: String,
    #[serde(rename = "productName")]
    pub product_name: String,
    #[serde(rename = "redeemingAmount")]
    pub redeeming_amount: String,
    #[serde(rename = "todayPurchasedAmount")]
    pub today_purchased_amount: String,
    #[serde(rename = "totalAmount")]
    pub total_amount: String,
    #[serde(rename = "totalInterest")]
    pub total_interest: String,
}

impl SapiV1LendingDailyTokenPositionGet200ResponseInner {
    pub fn new(annual_interest_rate: String, asset: String, avg_annual_interest_rate: String, can_redeem: bool, daily_interest_rate: String, free_amount: String, freeze_amount: String, locked_amount: String, product_id: String, product_name: String, redeeming_amount: String, today_purchased_amount: String, total_amount: String, total_interest: String) -> SapiV1LendingDailyTokenPositionGet200ResponseInner {
        SapiV1LendingDailyTokenPositionGet200ResponseInner {
            annual_interest_rate,
            asset,
            avg_annual_interest_rate,
            can_redeem,
            daily_interest_rate,
            free_amount,
            freeze_amount,
            locked_amount,
            product_id,
            product_name,
            redeeming_amount,
            today_purchased_amount,
            total_amount,
            total_interest,
        }
    }
}


