/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BswapAddLiquidityPreviewSingle {
    #[serde(rename = "quoteAsset")]
    pub quote_asset: String,
    #[serde(rename = "quoteAmt")]
    pub quote_amt: i64,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "share")]
    pub share: f64,
    #[serde(rename = "slippage")]
    pub slippage: f64,
    #[serde(rename = "fee")]
    pub fee: f64,
}

impl BswapAddLiquidityPreviewSingle {
    pub fn new(quote_asset: String, quote_amt: i64, price: f64, share: f64, slippage: f64, fee: f64) -> BswapAddLiquidityPreviewSingle {
        BswapAddLiquidityPreviewSingle {
            quote_asset,
            quote_amt,
            price,
            share,
            slippage,
            fee,
        }
    }
}


