/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BswapAddLiquidityPreviewCombination {
    #[serde(rename = "quoteAsset")]
    pub quote_asset: String,
    #[serde(rename = "baseAsset")]
    pub base_asset: String,
    #[serde(rename = "quoteAmt")]
    pub quote_amt: i64,
    #[serde(rename = "baseAmt")]
    pub base_amt: i64,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "share")]
    pub share: f64,
}

impl BswapAddLiquidityPreviewCombination {
    pub fn new(quote_asset: String, base_asset: String, quote_amt: i64, base_amt: i64, price: f64, share: f64) -> BswapAddLiquidityPreviewCombination {
        BswapAddLiquidityPreviewCombination {
            quote_asset,
            base_asset,
            quote_amt,
            base_amt,
            price,
            share,
        }
    }
}


