/*
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SavingsFlexibleRedemptionRecordInner {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "createTime")]
    pub create_time: i64,
    #[serde(rename = "principal")]
    pub principal: String,
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "projectName")]
    pub project_name: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SavingsFlexibleRedemptionRecordInner {
    pub fn new(amount: String, asset: String, create_time: i64, principal: String, project_id: String, project_name: String, status: String, r#type: String) -> SavingsFlexibleRedemptionRecordInner {
        SavingsFlexibleRedemptionRecordInner {
            amount,
            asset,
            create_time,
            principal,
            project_id,
            project_name,
            status,
            r#type,
        }
    }
}


